// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/generate": {
            "post": {
                "description": "Generates a test case based on the user prompt. The request will be processed by the LLM and returned in a unified response format.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Generate"
                ],
                "summary": "Generate test case using LLM",
                "parameters": [
                    {
                        "description": "Request body containing test cases",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with generated test case",
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateResult"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "Internal server error or LLM request failed",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AllureMetadata": {
            "type": "object",
            "properties": {
                "feature": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "manual": {
                    "type": "boolean"
                },
                "story": {
                    "type": "string"
                },
                "tag": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.Case": {
            "type": "object",
            "properties": {
                "allure_metadata": {
                    "$ref": "#/definitions/dto.AllureMetadata"
                },
                "user_prompt": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.GenerateBody": {
            "type": "object",
            "properties": {
                "cases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Case"
                    }
                }
            }
        },
        "dto.GenerateResult": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created": {
                    "type": "integer"
                },
                "refusal": {
                    "type": "string"
                },
                "stop_reason": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "TestOps Copilot",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
